# Generated by Django 4.1 on 2022-08-29 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhoneCertification",
            fields=[
                ("created_at", models.DateTimeField(auto_created=True, auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("user_name", models.CharField(max_length=100, verbose_name="성함")),
                (
                    "phone_number",
                    models.CharField(max_length=20, verbose_name="휴대폰 번호"),
                ),
                ("date_of_birth", models.DateField(verbose_name="생년월일")),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "M"), ("Female", "F")],
                        max_length=10,
                        verbose_name="성별",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mobile_carrier_code",
                    models.ForeignKey(
                        db_column="mobile_carrier_code",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.mobilecarrier",
                        to_field="code",
                        verbose_name="통신사 코드",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PhoneCertificationLog",
            fields=[
                ("created_at", models.DateTimeField(auto_created=True, auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=6, verbose_name="인증 코드")),
                (
                    "is_certificated",
                    models.BooleanField(default=False, verbose_name="인증 여부"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "phone_certification_id",
                    models.OneToOneField(
                        db_column="phone_certification_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="certification.phonecertification",
                        verbose_name="휴대폰 인증 id",
                    ),
                ),
            ],
        ),
    ]
