# Generated by Django 4.1 on 2022-08-29 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MobileCarrier",
            fields=[
                ("created_at", models.DateTimeField(auto_created=True, auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "code",
                    models.CharField(max_length=4, unique=True, verbose_name="통신사 코드"),
                ),
                ("name", models.CharField(max_length=20, verbose_name="통신사 명")),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                ("created_at", models.DateTimeField(auto_created=True, auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, verbose_name="사용자 명")),
                (
                    "nick_name",
                    models.CharField(max_length=100, unique=True, verbose_name="닉네임"),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, unique=True, verbose_name="이메일"),
                ),
                ("password", models.CharField(max_length=500, verbose_name="비밀번호")),
                (
                    "phone_number",
                    models.CharField(max_length=20, verbose_name="휴대폰 번호"),
                ),
                ("date_of_birth", models.DateField(verbose_name="생년월일")),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "M"), ("Female", "F")],
                        max_length=10,
                        verbose_name="성별",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mobile_carrier_code",
                    models.ForeignKey(
                        db_column="mobile_carrier_code",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.mobilecarrier",
                        to_field="code",
                        verbose_name="통신사 코드",
                    ),
                ),
            ],
        ),
    ]
