# Generated by Django 4.1 on 2022-08-29 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female")],
                max_length=10,
                verbose_name="성별",
            ),
        ),
    ]
