# Generated by Django 4.1 on 2022-08-27 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MobileCarrier",
            fields=[
                ("created_at", models.DateTimeField(auto_created=True, auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=4, unique=True)),
                ("name", models.CharField(max_length=20)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
